[project]
name = "captcha-solver"
version = "0.1.2"
description = "CAPTCHA solver AI"
requires-python = ">=3.13"
dependencies = [
    #"matplotlib",
    "notebook",
    "numpy",
    "pillow",
    "torch",
    "torchvision",
    "pytorch-triton-rocm",
    "questionary",
]

[tool.uv]
index-strategy = "unsafe-best-match"

[tool.uv.sources]
torch = [
    { index = "pytorch-rocm" },
]
torchvision = [
    { index = "pytorch-rocm" },
]
pytorch-triton-rocm = [
    { index = "pytorch-rocm" },
]

[[tool.uv.index]]
name = "pytorch-rocm"
url = "https://download.pytorch.org/whl/rocm6.4"
explicit = true
