[project]
name = "captcha-solver"
version = "0.2.2"
description = "CAPTCHA solver AI"
requires-python = ">=3.13"
dependencies = [
    # feature: frontend
    "questionary",
    "argparse",
    "tqdm",

    # feature: computate
    "numpy",
    "pillow",

    # feature: deeplearning
    #"scikit-learn",
    #"albumentations",
    "torch",
    "torchvision",

    # feature: save model with local timezone
    "tzdata",
]
